# -*- coding: utf-8 -*-
"""covid_data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OhsbHtfx4E2I2p5cetH-k39WyjbU9FrZ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("covid19_global_statistics_2026.csv")
print(df)

#Now lets do basic inspection

df.head() #this will give 1st 5 rows in dataset

df.head(10) # u can customize the number of rows also

df.tail(7) #it will give the last 7rows of the data set

df.info() #it gives all the basic info of the dataset

df.columns #it gives all the column names present in dataset

df.describe() #it gives statistically information of the dataset

#Now lets start with Data Cleaning

df.isnull().sum() # this gives number of null values in each column

#There are 2 options to handle these missing values :
# 1.removing all the missing values and 2.filling all the missing values
df.fillna(0,inplace=True) # this is used to fill all the missing values with 0
# df.dropna(inplace=True) = this is used to remove or delete all the missing values

df.isnull().sum() #AS all the values are filled there are no null values so the count will be zero

df.duplicated().sum()

df.drop_duplicates(inplace=True) #this will delete all the repeated rows and cols

df.dtypes #this gives the column and its datatype

#As above date column is considered as object we will change object into date-time datatype
df['date'] = pd.to_datetime(df['date'])

df.dtypes

#Now Lets Start with Exploratory Data Analysis

df.groupby('country').sum(numeric_only=True).sort_values(by='total_cases', ascending=False).head(1)
#this gives the country with highest cases
#Insight : All named country is having highest cases

df.groupby('country')['new_deaths'].sum().sort_values(ascending=False).head(1)
#this gives the country with max number of deaths
#insight : Spain is the country with more number of deaths

df.groupby('continent')['total_cases'].sum().sort_values(ascending=False)
#this gives all the total cases in each continent
#Insight : The continent names All is having max number of cases

df.groupby('country')['total_tests'].max().sort_values(ascending=False).head(10)
# this gives the country which done more number of testing
# Insight : USA has made more number of testings

#We will start Visualisations

top_cases = df.groupby('country')['total_cases'].max().sort_values(ascending=False).head(10)

top_cases.plot(kind='bar')
plt.title("Top 10 Countries by Total Cases")
plt.ylabel("Total Cases")
plt.show()
#It gives the visualisation for top 10 countries by total cases

continent_cases = df.groupby('continent')['total_cases'].sum()

continent_cases.plot(kind='pie', autopct='%1.1f%%')
plt.title("Continent-wise COVID Cases")
plt.ylabel("")
plt.show()
#It gives a pie chart for continent wise covid cases

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
sns.histplot(df['total_cases'], bins=30)
plt.title("Distribution of Total Cases")
plt.show()

sns.heatmap(df.corr(numeric_only=True), annot=True)
plt.show()

# Conclusion

# 1. USA performed highest testing
# 2. Spain recorded highest deaths
# 3. Cases are concentrated heavily in few countries
# 4. Testing and total cases show positive relationship